version: "3.1"
services:
  db:
    container_name: servidor_mysql
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: bookmedik
      MYSQL_USER: user_bookmedik
      MYSQL_PASSWORD: pass_bookmedik
      MYSQL_ROOT_PASSWORD: passwd
    volumes:
      - /opt/mysql_bookmedik:/var/lib/mysql

  bookmedik:
    container_name: bookmedik
    image: josedom24/bookmedik
    environment:
      MARIADB_USER: user_bookmedik
      MARIADB_PASS: pass_bookmedik
      MARIADB_NAME: bookmedik
      MARIADB_HOST: servidor_mysql
    restart: always
    ports:
      - 80:80
    depends_on:
      - db
    
    